### ISSUE TITLE
xml2db might generate illegal record names

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-EPICS-IOC-Adapter#1]
If the process variable name contains characters which are not allowed in epics record names (e.g. dot "."), xml2db will produce an illegal record file. Those characters should be replaced or an error should be generated.

**Comment by Amadrath** [comment]
Periods in PV names are now replaced with an underscore by default. The option -R | --replacePeriod was added, to change the replacement char. I.e. `xml2db -R ':' PathToXML PathToDB` replaces periods with colons.
